<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Version>3.0.0</Version>
    <Authors>HistoryLabs</Authors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TShock" Version="6.1.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" Aliases="BCryptNet" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
    <PackageReference Include="Discord.Net.Rest" Version="3.15.0" />
    <PackageReference Include="System.Linq.Async" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="$(OutDir)Discord*.dll" LinkBase="Resources" />
    <EmbeddedResource Include="$(OutDir)BCrypt*.dll" LinkBase="Resources" />
    <EmbeddedResource Include="$(OutDir)System.Interactive.Async.dll" LinkBase="Resources" />
    <EmbeddedResource Include="$(OutDir)System.Linq.Async.dll" LinkBase="Resources" />
    <EmbeddedResource Include="$(OutDir)Microsoft.Bcl.AsyncInterfaces.dll" LinkBase="Resources" />
  </ItemGroup>

</Project>
